#!/usr/bin/env bash
# install load balancer


# Update package repositories and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg >/dev/null
defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 100.25.19.221:80 check
    server web-02 18.233.65.175:80 check
EOF

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

# Verify HAProxy status
sudo systemctl status haproxy

