#!/usr/bin/env bash
# Configuration a ufw firewall to block to block all incoming traffics
# allow TCP ports 22, 8080, 80, and 443.


echo -e "Updating\n"

sudo apt-get update

echo -e "Installing UFW\n"

sudo apt-get install -y ufw

echo -e "configuring UFW...\n"

# Allow Outgoing and Deny Incoming
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow ports
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443

# Enable Fire Wall
sudo ufw enable
sudo ufw status verbose

echo -e "Process Completed.\n"
