#!/bin/bash

# Set key name
KEY_NAME="school"

# Set number of bits
BITS=4096

# Set passphrase
PASSPHRASE="betty"

# Generate RSA key pair
ssh-keygen -t rsa -b $BITS -C "$USER@$HOSTNAME" -f $KEY_NAME -N "$PASSPHRASE"

# Display success message
echo "RSA key pair generated successfully."

