#!/usr/bin/env bash

# Change directory to the ~/.ssh directory
cd ~/.ssh || exit

# Start SSH agent
eval $(ssh-agent)

# Add SSH private key to agent
ssh-add school

# SSH into the server
ssh -i school ubuntu@54.237.70.148

